name: Lockfile Check
on:
  push:
    branches: [main]
  pull_request: 

jobs:
  verify-lockfile:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出代码

      - name: Get PNPM version
        id: pnpm-version
        run: |
          VERSION=$(jq -r '.packageManager | split("@")[1]' package.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
      - name: Setup PNPM
        uses: pnpm/action-setup@v4 # 安装 pnpm
        with:
          version: ${{ steps.pnpm-version.outputs.version }}       # 指定 pnpm 版本（需与本地一致）
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0         # 指定 Node 版本（与项目一致）
          cache: 'pnpm'

      - name: Check Lockfile
        run: pnpm install --frozen-lockfile  # 核心检查命令